/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// Alpha vantage Api Key: 57RT1I8QVLFZ5KBV
// polygon API key: fpmMLn3k05p0MmW42QNvohFZ6rv7VNPJ
// Finage API key: API_KEY246OEREO7FCXK3FU4QIZ72HO174X5UDD
package dowjones_data;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.util.EntityUtils;

import java.io.IOException;
import java.util.LinkedList;
import java.util.Queue;

public class App {
    private static final String API_KEY = "API_KEY246OEREO7FCXK3FU4QIZ72HO174X5UDD";
    private static final String SYMBOL = "AAPL"; // Replace with the stock symbol you want to fetch

    public static void main(String[] args) {
        Queue<Double> stockPrices = new LinkedList<>();
        double sum = 0.0;

        while (true) {
            double currentPrice = fetchStockPrice();
            stockPrices.add(currentPrice);
            sum += currentPrice;

            if (stockPrices.size() > 5) {
                double removedPrice = stockPrices.poll();
                sum -= removedPrice;
            }

            double averagePrice = sum / stockPrices.size();
            System.out.println("Stock Price: " + currentPrice);
            System.out.println("Average Price: " + averagePrice);

            try {
                Thread.sleep(5000); // Wait for 5 seconds
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }

    private static double fetchStockPrice() {
        String url = "https://api.finage.co.uk/last/stock/" + SYMBOL + "?apikey=" + API_KEY;

        try {
            HttpClient httpClient = HttpClients.createDefault();
            HttpGet request = new HttpGet(url);
            String response = EntityUtils.toString(httpClient.execute(request).getEntity());
            System.out.println("Response: " + response); // Print the raw response
            
            JsonObject jsonObject = JsonParser.parseString(response).getAsJsonObject();
            double currentPrice = jsonObject.get("ask").getAsDouble(); // Use "ask" instead of "price"
            return currentPrice;
        } catch (IOException e) {
            e.printStackTrace();
        }

        return 0.0;
    }
}
